### ISSUE TITLE
Compute node monitoring and graphs (API & GUI) [meta]

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#13]
Implement advanced compute node monitoring and graphs in the Danube Cloud API and GUI.
The main idea behind this task is to further integrate the monitoring system into Danube Cloud.

Monitoring items: api/mon/node/graphs.py

## CPU tab

  - CPU utilization
    - items: `['system.cpu.util[,user,]', 'system.cpu.util[,system,]']`
    - stacked graph

  - 1-minute load average
    - items: `['system.cpu.load[,avg1]']`
    
  - CPU jumps
    - items: `['system.cpu.switches', 'system.cpu.intr']`
    

## Memory tab

**Comment by mbag** [comment]
There are several sub-tasks that need to be done. I've tried to put them in order so that those needed later on are done first:  
- [ ] In `api/mon/zabbix.py` add **node_history** method to **Zabbix** class, method will be similar to **vm_history**.
      In `api/mon/node/tasks.py` ass **mon_node_history** task  
- [ ] In `vms/models/node.py` in class **Node** add method **is_zabbix_sync_active()**
- [ ] Create new `graphs.py` for node monitoring based on `api/mon/vm/graphs.py`; factor out those things that are shared by both of these files, and place them into the new _abstract_ classes/functions in `api/mon/graphs.py`
- [ ] Add **mon_node_history()** to `api/mon/node/views.py`  
      Implement class **MonNodeHistorySerializer** `api/mon/node/serializers.py`
      Implement class **NodeHistoryView** to `api/mon/node/api_views.py`
